gitlab-runner:
  container_name: gitlab-runner
  image: 'gitlab/gitlab-runner:latest'
  restart: always
  privileged: true
  volumes:
    - './gitlab-runner/config:/etc/gitlab-runner'
    - '/var/run/docker.sock:/var/run/docker.sock'